

import { createApi, fetchBaseQuery } from '@reduxjs/toolkit/query/react';

// Define the API slice
const contactApi = createApi({
  reducerPath: 'contactApi',
  baseQuery: fetchBaseQuery({
    baseUrl: 'https://localhost:7090/api/', // Update with your API base URL
  }),
  endpoints: (builder) => ({
    contactUser: builder.mutation({
      query: (userData) => ({
        url: 'UserInfo', // Update with your contact endpoint
        method: 'POST',
        body: userData,
      }),
    }),
  }),
});

// Export the hooks generated by the API slice
export const { useContactUserMutation } = contactApi;

// Export the API slice
export default contactApi;

